# Product device tree and matching overlay
dtb-$(CONFIG_ARCH_SPRD) += istudy-c10.dtb
dtb-$(CONFIG_ARCH_SPRD) += istudy-c10-overlay.dtbo
istudy-c10-overlay.dtbo-base := istudy-c10.dtb
DTC_FLAGS_istudy-c10 += -@
DTC_FLAGS_istudy-c10-overlay += -@
