# SPRD Audio Memory Manager Support
SPRD_SOUND_TREE                         := $(srctree)/sound/soc/sprd/roc1/
subdir-ccflags-y                        += -I$(SPRD_SOUND_TREE)/include/

obj-$(CONFIG_SPRD_AUDIO_MEMORY_MANAGER)  += audio_mem.o
