#
# Makefile for sensor hub drivers.
#
obj-$(CONFIG_SPRD_SENSOR_HUB)    += sensorhub.o
sensorhub-objs := shub_core.o shub_protocol.o shub_comm.o
obj-$(CONFIG_SPRD_SENSOR_HUB_C8PRO_FACTORY) += c8pro_cm4.o
