#
# Makefile for sensor hub drivers.
#
obj-$(CONFIG_SPRD_SENSOR_HUB)    += sensorhub.o
sensorhub-objs := shub_core.o shub_protocol.o shub_comm.o
obj-$(CONFIG_MITOCHODRIA_CM4_LOADER) += mitochodria_cm4.o
