obj-$(CONFIG_SPRD_APHANG) 		+= sprd_aphang.o
sprd_aphang-$(CONFIG_SPRD_APHANG) 	+= sprd_wdf.o sprd_wdh.o

# Allow building wdf standalone (4.14 path, used by the factory config)
obj-$(CONFIG_SPRD_WDF) += sprd_wdf.o

obj-$(CONFIG_SPRD_WDH) += sprd_wdh.o
